### ISSUE TITLE
Difficulty Max 64k?

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo-c-miner#4]
Looks like a maximum of two bytes of the integer difficulty go in to the 66 byte buffer that gets hashed. Is that correct?

https://github.com/zack-bitcoin/amoveo-c-miner/blob/7561112eac0c4d775121406f8472d3aed5a338f8/amoveo_pow.c#L61
https://github.com/zack-bitcoin/amoveo-c-miner/blob/7561112eac0c4d775121406f8472d3aed5a338f8/amoveo_pow.c#L62

If that's not correct, should the 66 byte buffer become larger (fixed) or is that length dynamic with the difficulty's size?

The pool appears to verify the hash using the difficulty. Does that have similar issue or is it good?

**Comment by zack-bitcoin** [comment]
yeah, we store the difficulty in 2 bytes. So that means that there are about 65535 different possible values for the difficulty.
Bitcoin uses 4 bytes for this value: https://en.bitcoin.it/wiki/Protocol_documentation#Block_Headers

In Amoveo the difficulty is stored in scientific notation.
It is explained in here.
https://github.com/BumblebeeBat/pink_crypto/blob/master/src/pow.erl

Basically the value is (2 ^ Byte1) * (256 + Byte2) div 256

So increasing the first byte by 1 doubles the difficulty.
increasing the second byte by 1 increases the difficulty by about 0.3%
